"""empty message

Revision ID: 106cf8553f13
Revises: acb1bd0886cd
Create Date: 2023-01-12 20:11:30.614891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106cf8553f13'
down_revision = 'acb1bd0886cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
