"""empty message

Revision ID: 12559b66561e
Revises: 2da9af8c7e19
Create Date: 2023-01-12 14:16:40.248387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12559b66561e'
down_revision = '2da9af8c7e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
