"""empty message

Revision ID: 589e0baaa2a2
Revises: c5f1d2f52f53
Create Date: 2023-01-12 19:27:30.131933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589e0baaa2a2'
down_revision = 'c5f1d2f52f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
