version: '3.9'

services:
  app:
    build:
      context: .
      target: base
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "flask db migrate &&
      flask db upgrade &&
      flask --debug run --host=0.0.0.0 --port=8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=storesdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432
  redis:
     image: redislabs/redismod
     ports:
       - 6379:6379
  worker:
      build:
        context: .
        target: base
        args:
          - DEV=true
      depends_on:
          - redis
      command: rq worker --url redis://redis:6379 emails
      links:
          - redis

volumes:
  dev-db-data: